### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by michaelmior** [pgbovine/opt-cpp-backend#11]
The demo looks great! I can manage to produce trace files that look correct. Is there documentation anywhere on how to provide these traces to the frontend so I can actually see the visualization? Even if it's not possible for students to visualize arbitrary programs, it would be great to be able to give them some examples!

**Comment by michaelmior** [comment]
I noticed that I should be able to dump the trace into `test-trace.js` in the v3 frontend. However, this gives me an exception even on a trace of the following trivial program.

```c
int main() {
    for (int i = 0; i < 10; i++) {
      i++;
    }
}
```

**Comment by Levara** [comment]
I managed to run the visualizer by replacing the tracefile in rosseta demo repo with the generated traces. 
I wget-ed the C demo and just replaced the trace file with the generated one.

**Comment by marianomendez** [comment]
Hi,
    I see the tool and I think is wonderful, I teach C in the University of Buenos Aires and this kind of visualization is great for student. I would like to collaborate with the C language It would be great to 
to have :

1- Just a more detailed documentation on how to transform c programs by using valgrind and then how to transform the Valgrind trac into Json undertandable to the frontend. I supouse that the vg_to_opt_trace.py makes this work, but just a little explanation about the process will be very much apreciated.

2- I am interesting in collaborate to enable the C language feature please contact me at marianomendez@gmail.com.

3- I offer my time to write a detailed documentation about the entire process but I need more information about it.

regards
 Mariano Mendez

**Comment by Levara** [comment]
Check out the `tests` subfolder. Inside is the `Makefile` in which you can see how to run Valgrind to generate the trace. 
You should probably run Linux, because I have no idea how to run this on Windows. 

- Let's say you are in a folder on your computer, for example `~/visualize/`
- You clone the repo to this folder, so now all the code for the backend will be in `~/visualize/opt-cpp-backend`.
- You should now compile and make the binaries. Try running the auto-everything.sh and everything should be compiled. If not, you will probably have to manually make the valgrind in the repo. 
- After Valgrind is compiled, go back to your starting folder: `~/visualize/`
- Let's say that you have a test C program in your starting folder: `~/visualize/test.c`
- First you need to generate the program binary. To do this run: `gcc -ggdb -O0 -fno-omit-frame-pointer test.c -lm -o test`
- Now you feed the generated binary to Valgrind: `./opt-cpp-backend/valgrind-3.11.0/inst/bin/valgrind --tool=memcheck --source-filename=test.c --trace-filename=test.vgtrace ./test`
- The above command will run your program and generate trace. Start with a simple program that does not require input from stdin, because that will halt the Valgrind and you may not notice it and think it does not work.
- After Valgrind generated the trace file, you should run it through converter to get json: `python opt-cpp-backend/vg_to_opt_trace.py --create_jsvar=trace  test   1>test.trace`

After the last step you have the .json trace you can visualize. 
I didn't try to run anything else, I just downloaded the whole http://pgbovine.net/rosetta/c-demo.html page, and in the .html source changed the path to the trace file to the one I generated. And now it works. 

Here are some examples I generated: c-vis.levara.net. 
On the page are visualizations of the problems from regional Informatics competition, and not all of them could be visualized, but for every link it is written which can be visualized.

Some of the thing still not implemented in this backend are Unions, 2D arrays and stdin-stdout. Visualizer just ignores stdout from your program, does not show it anywhere.

Hope this helps! If you have any more questions, feel free to ask, I'll try to help as much as I can.

**Comment by michaelmior** [comment]
Thanks so much for the documentation! This definitely helped me. I will definitely recommend that we use this for our introductory C programming course in the coming term. I think it will incredibly useful for students. (Especially when they start seeing pointers for the first time!)

**Comment by marianomendez** [comment]
Great ! Thank you ! I will try and report ot. I have some resourses available to help with the proyect, I would like to know to whom I hate to contact.
Thank you for the response
Mariano

**Comment by pgbovine** [comment]
Thanks for contributing, everyone! This project wasn't ready for public display yet, even though I made the code freely available. Sorry again that it hasn't been well documented yet, since I just started this as a prototype last year but haven't had a chance to work on it in a long time.

**Comment by marianomendez** [comment]
I am very interesting in contributing on this project, I think it is a very visual approach to C programming. So I am Offering my time and resources to contribute with the project. My Name is Mariano Mendez I am Phd In Computer Science and Msc in Software Engineering, I am teaching C programming at the Universidad de Buenos Aires and I am  would like to help in this project. so if you are interested please contact me.  

best regards 
Martiano

**Comment by pgbovine** [comment]
This isn't a fully satisfying answer, but the Makefiles and Dockerfile in this repo should give you some idea of how to run things. Also, the site is now live!

http://pythontutor.com/visualize.html#py=c
