### ISSUE TITLE
Vanishing heap data - maybe eliminate redundant line after function returns to same line as originally called from

### ISSUE THREAD

**Issue by michaelmior** [pgbovine/opt-cpp-backend#33]
When a function returns a pointer to heap allocated memory, the memory disappears from the heap for one step before reappearing when a variable in the calling function starts pointing to it.

Example

``` C
void* foo() {
  void *x = malloc(1);
  return x;
} // allocated memory disappears from the heap here

int main() {
  void *x = foo(); // memory reappears here
  free(x);
}
```

So far I've hacked around this by just checking the resulting JSON object for this case and copying the heap data over to the intermediate step but it seems like this should be the default behaviour.

**Comment by pgbovine** [comment]
Yep that makes sense since I start traversing from stack/heap variables. It is confusing, though, i agree. will think more

**Comment by pgbovine** [comment]
sorry this probably won't be displayed properly in the way that you want. i see the problem, but it's hard to change it so that heap blocks persist across function calls without disappearing and reappearing. thanks for reporting!

**Comment by michaelmior** [comment]
Fair enough. I'll just have to stick with my hack that patches things up for my needs. I just check if an address appears in both the previous and next step's heap and if it does, I copy it into the current step. There might be some edge cases where this breaks, but it's working ok for now.

**Comment by pgbovine** [comment]
Thanks for understanding. The way the visualizer frontend is currently structured, i can't display dangling memory blocks without at least 1 variable pointing to them, since I traverse the object graph starting at variables.

**Comment by pgbovine** [comment]
quick question, Michael (@michaelmior) . one hack i'm considering is eliminating Step 7 of this example https://goo.gl/iA3uKm -- i.e., the heuristic is that after a function call returns, just skip one step and display the next one after that, since it takes one extra step for the return value to be assigned to the left-hand-side of the '=' in the assignment statement. If I eliminate that step, it will make the "disappearing/reappearing block" problem go away, and may be more elegant, since that extra step isn't informative at all. it's just a byproduct of using Valgrind -- its tracing is too fine-grained. what do you think about that idea? (let me know if my explanation is unclear -- late night)

**Comment by michaelmior** [comment]
I'm getting a timeout now when I try to run that. But I assume you mean the step after the function finishes executing and before returning control to the calling function. I think getting rid of that step would be fine. I don't really see at as adding any value to the understanding of the execution. And if that solves the disappearing heap problem, then that's a nice bonus!

**Comment by pgbovine** [comment]
Yep, sorry about timeouts; my server is wimpy; it usually works if you try again a minute later.

I'll hack something up and let you know; I still need some heuristics because sometimes I don't want to skip the step after the return, if the return value isn't being assigned to anything (because then Valgrind does the right thing and continues onto the next line).

**Comment by pgbovine** [comment]
Seems to work now, check out: https://goo.gl/iA3uKm

**Comment by michaelmior** [comment]
Awesome, thanks!
